# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-15 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0002_deploydcos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploydcos',
            name='deploy_time',
            field=models.DateTimeField(auto_now=True, verbose_name='\u4e0a\u7ebf\u5f00\u59cb\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='deploydcos',
            name='status',
            field=models.IntegerField(choices=[(0, '\u53d1\u5e03'), (1, '\u53d6\u6d88\u53d1\u5e03')], default=0, verbose_name='\u4e0a\u7ebf\u72b6\u6001'),
        ),
    ]
