# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-16 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0006_auto_20180516_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploydcos',
            name='status',
            field=models.IntegerField(choices=[(0, '\u5f85\u53d1\u5e03'), (1, '\u5df2\u53d1\u5e03'), (2, '\u53d6\u6d88\u53d1\u5e03')], default=0, verbose_name='\u4e0a\u7ebf\u72b6\u6001'),
        ),
    ]
