# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-17 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0007_auto_20180516_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploydcos',
            name='buildstatus',
            field=models.CharField(default='SUCCESS', max_length=40, verbose_name='\u9879\u76ee\u6784\u5efa\u72b6\u6001'),
        ),
    ]
