# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-21 09:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deploy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='\u9879\u76ee\u540d\u79f0')),
                ('project_version', models.CharField(max_length=40, verbose_name='\u9879\u76ee\u7248\u672c')),
                ('version_desc', models.CharField(max_length=100, verbose_name='\u7248\u672c\u63cf\u8ff0')),
                ('applicant_id', models.IntegerField(default=1, verbose_name='\u7533\u8bf7\u4eba')),
                ('update_detail', models.TextField(verbose_name='\u66f4\u65b0\u8be6\u60c5')),
                ('status', models.IntegerField(choices=[(0, '\u7533\u8bf7'), (1, '\u7070\u5ea6'), (2, '\u4e0a\u7ebf'), (3, '\u53d6\u6d88\u4e0a\u7ebf')], default=0, verbose_name='\u4e0a\u7ebf\u72b6\u6001')),
                ('apply_time', models.DateTimeField(auto_now_add=True, verbose_name='\u7533\u8bf7\u65f6\u95f4')),
                ('deploy_time', models.DateTimeField(auto_now=True, verbose_name='\u4e0a\u7ebf\u5b8c\u6210\u65f6\u95f4')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u6307\u6d3e\u7ed9')),
            ],
        ),
    ]
