# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-25 10:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_release', '0002_auto_20180425_1806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deploy',
            old_name='applicant_id',
            new_name='applicant',
        ),
    ]
