# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-15 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deploydcos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobname', models.CharField(max_length=40, verbose_name='\u9879\u76ee\u540d\u79f0')),
                ('status', models.IntegerField(choices=[(2, '\u53d1\u5e03'), (3, '\u53d6\u6d88\u53d1\u5e03')], default=0, verbose_name='\u4e0a\u7ebf\u72b6\u6001')),
                ('deploy_time', models.DateTimeField(auto_now=True, verbose_name='\u4e0a\u7ebf\u5b8c\u6210\u65f6\u95f4')),
            ],
        ),
    ]
